version: '3.8'

services:
  app:
    build: .
    container_name: pioneerpicsel-app
    ports:
      - "8080:8080"
    depends_on:
      - db
      - redis
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/pioneerpicsel
      SPRING_DATASOURCE_USERNAME: cuba
      SPRING_DATASOURCE_PASSWORD: cuba
      SPRING_REDIS_HOST: redis
      SPRING_REDIS_PORT: 6379
      JWT_SECRET: MySecretKey123456789
      JWT_EXPIRATION: 3600000
    networks:
      - app-network

  db:
    image: postgres:15
    container_name: pioneerpicsel-db
    restart: always
    environment:
      POSTGRES_DB: pioneerpicsel
      POSTGRES_USER: cuba
      POSTGRES_PASSWORD: cuba
    ports:
      - "5432:5432"
    networks:
      - app-network

  redis:
    image: redis:7
    container_name: pioneerpicsel-redis
    restart: always
    ports:
      - "6379:6379"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
